- name: Set up SSL and configure Docker containers
  hosts: localhost
  connection: local
  tasks:
    - name: Copy SSL certificates to Docker volumes
      copy:
        src: ../certs/
        dest: /etc/ssl/certs

    - name: Ensure client container is started
      docker_container:
        name: mern-client
        image: mern-client
        state: started
        ports:
          - "0.0.0.0:443:443"
        volumes:
          - /etc/ssl/certs:/etc/ssl/certs  # Mount certificates from host to container
        env:
          HTTPS: "true"
          SSL_CERT_FILE: "/etc/ssl/certs/localhost.crt"
          SSL_KEY_FILE: "/etc/ssl/certs/localhost.key"

    - name: Ensure server container is started
      docker_container:
        name: mern-server
        image: mern-server
        state: started
        ports:
          - "0.0.0.0:8080:8080"  # Bind to all interfaces